### ISSUE TITLE
SREQ-325 ready for submission 

### ISSUE THREAD

**Issue by AnnikaWeimer** [StanfordBioinformatics/pulsar_lims#251]
https://pulsar-encode.herokuapp.com/sequencing_requests/325/libraries_index

Hi Tao, those libraries can be submitted to the portal. Thanks!

**Comment by twang15** [comment]
### Sub-tasks:
#254 
#255 
#256 
#257 
#258 
#259 
#260

**Comment by twang15** [comment]
Hi Annika,
 
SREQ-325 are for snRNA experiments, which DCC requires strand specificity.
Should we set them to forward or reverse for both reads or differently for each read?
 
Best,
Tao

**Comment by AnnikaWeimer** [comment]
Yes, you can specify: forward

Thanks.
__________________________________________

Annika K. Weimer, PhD
Project Lead ENCODE - Snyder lab

Stanford Medicine – Department of Genetics
Center for Genomics and Personalized Medicine

***@***.******@***.***>
+1 ‭(650) 724-4044

On Apr 29, 2021, at 10:15 PM, twang15 ***@***.******@***.***>> wrote:



Hi Annika,

SREQ-325 are for snRNA experiments, which DCC requires strand specificity.
Should we set them to forward or reverse for both reads or differently for each read?

Best,
Tao

**Comment by twang15** [comment]
For both reads?

**Comment by AnnikaWeimer** [comment]
It has 2 reads because it’s paired-end seq (which means the sequence is read from left to right and from right to left to get better coverage, but this is both on the same strand) but this is independent of the strand specificity. So yes, for both reads.

Thanks, Annika
__________________________________________

Annika K. Weimer, PhD
Project Lead ENCODE - Snyder lab

Stanford Medicine – Department of Genetics
Center for Genomics and Personalized Medicine

***@***.******@***.***>
+1 ‭(650) 724-4044

On May 3, 2021, at 10:16 AM, twang15 ***@***.******@***.***>> wrote:



For both reads?

**Comment by twang15** [comment]
> It has 2 reads because it’s paired-end seq (which means the sequence is read from left to right and from right to left to get better coverage, but this is both on the same strand) but this is independent of the strand specificity. So yes, for both reads. Thanks, Annika
> […](#)

Great, thanks for your confirmation.

**Comment by twang15** [comment]
Annika, for snRNA library, 

the field "Strand Specific?"  has to be set to **true** in the future.
e.g., https://pulsar-encode.herokuapp.com/libraries/11477

**Comment by twang15** [comment]
Hi Annika,

SREQ-325 has been submitted successfully to the portal.

Best,
Tao
